### ISSUE TITLE
CI: Helm chart should not be created if the container creation fails

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#136]
Currently there seems to be no link between the two actions

update: description - from @callumforrester 

Typically in a Github release pipeline, you want actions to depend on one another so that broken artefacts are not published, for example there is no point in uploading to PyPi or publishing a container image if the tests won't even pass.
Currently we have a Github actions job for publishing the helm chart on a release, and it doesn't seem to have any dependencies because it will try to package and publish a chart even if other jobs fail. It should be one of the last steps in the pipeline and should depend on the container build at the very least.

## Acceptance Criteria

-     Helm publishing job depends on container successfully building and publishing
-     If the container fails, no new helm chart is published

**Comment by DiamondJoseph** [comment]
Also should wait until the container is finished creating

**Comment by keithralphs** [comment]
Should we restructure using reusable workflows to achieve this, now that we know they work?

**Comment by callumforrester** [comment]
Potentially, there is also an argument for restructuring upstream in https://github.com/DiamondLightSource/python3-pip-skeleton and merging to here. @gilesknap any thoughts?

**Comment by callumforrester** [comment]
Plans for https://github.com/DiamondLightSource/python-copier-template align with this so should be resolved by https://github.com/DiamondLightSource/blueapi/issues/359

**Comment by stan-dot** [comment]
@callumforrester  the issue description is unclear, I guess this is solved now with https://github.com/DiamondLightSource/blueapi/issues/359

**Comment by callumforrester** [comment]
@stan-dot this issue is not resolved and I agree it needs more description:

Typically in a Github release pipeline, you want actions to depend on one another so that broken artefacts are not published, for example there is no point in uploading to PyPi or publishing a container image if the tests won't even pass.
Currently we have a Github actions job for publishing the helm chart on a release, and it doesn't seem to have any dependencies because it will try to package and publish a chart even if other jobs fail. It should be one of the last steps in the pipeline and should depend on the container build at the very least.

## Acceptance Criteria

- Helm publishing job depends on container successfully building and publishing
- If the container fails, no new helm chart is published

**Comment by DiamondJoseph** [comment]
We might still want to *create* a Helm chart as part of an earlier step in case we make a breaking change to it, but not publish unless everything works.

**Comment by callumforrester** [comment]
Agreed, there should be a job to lint the chart and another one to publish it
